import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReactQueryProvider from "../provider/ReactQueryProvider";

import "../styles/global.css";
import "../styles/components.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={inter.className}>{children}</body>
      </ReactQueryProvider>
    </html>
  );
}
